name: Build zlib windows

on:
  workflow_dispatch:
    inputs:
      zlibVersion:
        description: "zlib version to download and build, eg 1.3.1"
        required: true
        default: "1.3.1"
        type: string

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86
      

    - name: Enable Developer Command Prompt for Microsoft Visual C++ (vcvarsall)
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
          arch: x86
      

    - name: Download zlib source
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile zlib.tar.gz -Uri "https://zlib.net/zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}.tar.gz"
        tar -xf zlib.tar.gz

    - name: Build zlib
      shell: pwsh
      working-directory: zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}/contrib/vstudio/vc17
      run: |
        msbuild zlibvc.sln /t:zlibstat /p:Configuration=Release /p:Platform=Win32

    - uses: actions/upload-artifact@v4.3.1
      with:
        name: zlib-windows-x32
        path: zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}
  build2:
    runs-on: windows-2022
    steps:
    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
      

    - name: Enable Developer Command Prompt for Microsoft Visual C++ (vcvarsall)
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
          arch: x64
      

    - name: Download zlib source
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile zlib.tar.gz -Uri "https://zlib.net/zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}.tar.gz"
        tar -xf zlib.tar.gz

    - name: Build zlib
      shell: pwsh
      working-directory: zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}/contrib/vstudio/vc17
      run: |
        msbuild zlibvc.sln /t:zlibstat /p:Configuration=Release /p:Platform=x64

    - uses: actions/upload-artifact@v4.3.1
      with:
        name: zlib-windows-x64
        path: zlib-${{ github.event.inputs.zlibVersion  || '1.3.1'  }}
